version: '3.7'
services:
  postgres:
    image: 'postgres:16'
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=checkbox_system
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./ch_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/
    ports:
      - "8123:8123" # Or any other desired port for the ClickHouse client
    ulimits:
      nofile: 262144
    restart: unless-stopped
  web:
    env_file:
    - .env
    build:
      context: .
      dockerfile: dev.Dockerfile
    links:
      - postgres
    container_name: task-app-express
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PGHOST=postgres
      - CLICKHOUSE_HOST=http://clickhouse:8123
    volumes:
      - ./:/app
    restart: unless-stopped
