version: '3.7'
services:
  postgres:
    image: 'postgres:10.7'
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=checkbox-system
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    env_file:
    - .env
    build:
      context: .
      dockerfile: dev.Dockerfile
    links:
      - postgres
    container_name: task-app-express
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PGHOST=postgres
    volumes:
      - ./:/app
