version: '3.7'
services:
  postgres:
    image: 'postgres:16.7'
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=checkbox-system
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  clickhouse:
    image: clickhouse/clickhouse-server
    volumes:
      - ./ch_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/
    ulimits:
      nofile: 262144
  web:
    env_file:
    - .env
    build:
      context: .
      dockerfile: dev.Dockerfile
    links:
      - postgres
    container_name: task-app-express
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PGHOST=postgres
    volumes:
      - ./:/app
